export const SETTINGS_DEFAULTS = {
  'stt.language': 'en',
  'wake_word.engine': 'openwakeword',
  'wake_word.sensitivity': 0.5,
  'window.start_with_os': false,
  'window.always_on_top': false,
  'window.hotkey': 'Ctrl+Space',
  'window.start_minimized': false,

  'audio.microphone_device': 'default',
  'audio.speaker_device': 'default',
  'tts.voice_profile': 'jarvis_classic',
  'tts.speaking_rate': 1,
  'tts.volume': 0.8,
  'tts.primary': 'piper',
  'stt.engine': 'moonshine',
  'stt.model': 'tiny',
  'audio.silence_stop_seconds': 2,

  'brain.providers.default_provider': 'gemini',
  'brain.models.claude': 'claude-sonnet-4-20250514',
  'brain.models.gemini': 'gemini-2.5-flash',
  'brain.models.groq': 'llama-3.3-70b-versatile',
  'brain.models.openrouter': 'openai/gpt-4o-mini',
  'brain.models.ollama': 'llama3.2',
  'response.length': 'normal',
  'response.style': 'professional',
  'brain.short_term_turns': 30,
  'response.custom_prompt': '',
  'brain.token_budget': 4000,
  'brain.stream_chunks': false,

  'ui.theme': 'dark-sci-fi',
  'ui.accent': 'cyan',
  'ui.hud_style': 'arc-reactor',
  'ui.animation_speed': 1,
  'ui.reduced_animations': false,
  'window.opacity': 100,
  'window.font_size': 'normal',

  'auth.enabled': false,
  'auth.mode': 'passive',
  'auth.threshold': 'medium',
  'auth.liveness': 'sensitive_only',
  'auth.pin_fallback': true,
  'auth.session_timeout_minutes': 30,

  'api.anthropic': '',
  'api.gemini': '',
  'api.groq': '',
  'api.openrouter': '',
  'api.ollama': '',
  'api.elevenlabs': '',
  'api.brave': '',
}
